### ISSUE TITLE
no Setup.py

### ISSUE THREAD

**Issue by DeafAkula** [jerobado/mistermarket#1]
Hello,

Setup.py does not exist in the module. It can't be installed normally using pip install git.
is this normal?

**Comment by jerobado** [comment]
Hey! Thank you for opening an issue.

I haven't published this yet to PyPI thus `pip` command won't work, but it's something I want to do with this project.

I'm currently working on a different project right now but I will prioritize this one on the next release.  

You can keep this issue open for monitoring.
